name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: 
          cd CompressionAlgorithms && ./gradlew build
      - name: Run the tests
        run: 
          cd CompressionAlgorithms && ./gradlew jacocotestreport
    after_success:
      - bash <(curl -s https://codecov.io/bash)
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}